apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wildfire
  description: An example of a Backstage application.
  annotations:
    argocd/proxy-url: '/argocd/api2'
    argocd/app-selector: "tier=cluster"
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
